name: Sphinx Documentation Generation for Github Pages
on: [push]
jobs:
  Build-Sphinx-Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Build documentation
        run: cd sphinx && pip3 install -r requirements.txt && make html